name: Slimefun DEV

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          java-package: jdk
          architecture: x64
          cache: maven
      - name: Install local dependencies
        run: mvn clean install -DskipTests --errors -B
      - name: Codestyle check
        run: mvn -s .mvn/settings.xml -B spotless:check --errors
      - name: Build Slimefun
        run: mvn -s .mvn/settings.xml -B clean package --errors
      - name: Upload Slimefun-4-Folia jar
        uses: actions/upload-artifact@v4
        with:
          name: Slimefun-4-Folia
          path: target/*.jar