name: Slimefun DEV

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          java-package: jdk
          architecture: x64
          cache: maven

      - name: Install FoliaAdapter
        run: |
          ./mvnw install:install-file \
            -Dfile=ci-libs/FoliaAdapter-1.0-SNAPSHOT.jar \
            -DgroupId=com.molean \
            -DartifactId=FoliaAdapter \
            -Dversion=1.0-SNAPSHOT \
            -Dclassifier=dev \
            -Dpackaging=jar
      - name: Install dough-api
        run: |
          ./mvnw install:install-file \
            -Dfile=ci-libs/dough-api-1.3.1-Folia.jar \
            -DgroupId=io.github.baked-libs \
            -DartifactId=dough-api \
            -Dversion=1.3.1-Folia \
            -Dpackaging=jar
      - name: Codestyle check
        run: mvn -s .mvn/settings.xml -B spotless:check --errors
      - name: Build Slimefun
        run: mvn -s .mvn/settings.xml -B clean package --errors
      - name: Upload Slimefun-4-Folia jar
        uses: actions/upload-artifact@v4
        with:
          name: Slimefun-4-Folia
          path: target/*.jar